F_VENDAS = f"""
( SELECT
    ISNULL(SK_D_CLIENTE,0),
    ISNULL(SK_D_UNIDADE,-1),
    ISNULL(SK_D_IMOBILIARIA,0),
    ISNULL(SK_D_GERENTE,0),
    ISNULL(SK_D_SUPERVISOR,0),
    ISNULL(SK_D_CORRETOR,0),
    ISNULL(SK_D_ETAPA_VENDA,0),
    ISNULL(SK_D_STATUS_REPASSE,333),
    ISNULL(SK_D_USO,0),
    CAST(CONTRATO_SYS AS INT) AS NUMERO_CONTRATO_SYS,
    convert(DATE,DATA_ENTREGA_OBRA,111) AS DATA_ENTREGA_OBRA,
    convert(DATE,DATA_ENTREGA_CHAVES,111) AS DATA_ENTREGA_CHAVES,
    CASE WHEN DATA_DISTRATO='0000-00-00 00:00:00' THEN
    NULL
    ELSE
    convert(DATETIME,DATA_DISTRATO,111)
    END AS DATA_DISTRATO,
    cast(GRAU_INSTRUCAO as int) AS GRAU_INSTRUCAO
FROM 
    StgBild.STG_SYS_T_VENDA f_venda
JOIN DMGeral.D_CLIENTE dim_cli on (f_venda.EST_IN_CODIGO=dim_cli.CODIGO_SYS and f_venda.CPF_CNPJ=dim_cli.CPF_CNPJ)
LEFT JOIN DMGeral.D_UNIDADE dim_uni on f_venda.EST_IN_CODIGO=dim_uni.CODIGO_UNIDADE
LEFT JOIN DMGeral.D_IMOBILIARIA dim_imo on f_venda.CODIGO_IMOBILIARIA=dim_imo.CODIGO_IMOBILIARIA
LEFT JOIN DMGeral.D_GERENTE dim_gere on f_venda.CODIGO_GERENTE=dim_gere.CODIGO_GERENTE
LEFT JOIN DMGeral.D_SUPERVISOR dim_super on f_venda.CODIGO_SUPERVISOR=dim_super.CODIGO_SUPERVISOR
LEFT JOIN DMGeral.D_CORRETOR dim_corretor on f_venda.CODIGO_CORRETOR=dim_corretor.CODIGO_CORRETOR
LEFT JOIN DMGeral.D_ETAPA_VENDA dim_etapa_venda on f_venda.CODIGO_VENDA=dim_etapa_venda.CODIGO_VENDA
LEFT JOIN DMFinanceiro.D_STATUS_REPASSE dim_status_repasse on f_venda.STATUS_REPASSE=dim_status_repasse.CODIGO_STATUS_REPASSE
LEFT JOIN DMGeral.D_USO dim_uso on f_venda.CODIGO_USO=dim_uso.CODIGO_USO ) F_VENDAS
""".replace('\n', ' ').replace('\t', ' ').strip()