from .config import (SSMS_HOST, SSMS_DB, SSMS_PORT, SSMS_USER, SSMS_PSWD, ORACLE_MEGA_HOST, ORACLE_MEGA_DB, ORACLE_MEGA_PORT, ORACLE_MEGA_USER, ORACLE_MEGA_PSWD, ORACLE_MEGA_SERVICE)

__all__ = [
    "SSMS_HOST",
    "SSMS_DB",
    "SSMS_PORT",
    "SSMS_USER",
    "SSMS_PSWD",
    "ORACLE_MEGA_HOST",
    "ORACLE_MEGA_DB",
    "ORACLE_MEGA_PORT",
    "ORACLE_MEGA_USER",
    "ORACLE_MEGA_PSWD",
    "ORACLE_MEGA_SERVICE",
]