import os

SYS_DB = os.environ.get('MYSQL_DB')
SYS_HOST = os.environ.get('MYSQL_HOST')
SYS_PORT = os.environ.get('MYSQL_PORT')
SYS_USER = os.environ.get('MYSQL_USER')
SYS_PSWD = os.environ.get('MYSQL_PSWD')
SSMS_HOST = os.environ.get('SSMS_HOST')
SSMS_PORT = os.environ.get('SSMS_PORT')
SSMS_USER = os.environ.get('SSMS_USER')
SSMS_PSWD = os.environ.get('SSMS_PSWD')
ORACLE_MEGA_DB = os.environ.get('ORACLE_DB')
ORACLE_MEGA_HOST = os.environ.get('ORACLE_HOST')
ORACLE_MEGA_PORT = os.environ.get('ORACLE_PORT')
ORACLE_MEGA_USER = os.environ.get('ORACLE_USER')
ORACLE_MEGA_PSWD = os.environ.get('ORACLE_PSWD')
ORACLE_MEGA_SERVICE = os.environ.get('ORACLE_SERVICE')
